name: 'MetaMaker'
description: 'A GitHub Action to automatically generate metadata for a specific repository.'
inputs:
  repository:
    description: 'The name of the repository to gather the metadata for.'
    required: true
outputs:
  metadata:
    description: 'The built metadata object.'
runs:
  using: 'node16'
  main: 'index.js'
